"""
BadgesApi.py – Emits verifiable credentials in the Open Badges 3.0 format.

POST /api/badges/issue
"""

from __future__ import annotations

import logging
import uuid
from datetime import datetime, timezone

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

from ml_engine.openbadges import (
    Achievement,
    AchievementSubject,
    OpenBadgeCredential,
    Profile,
)

from api.core.Config import get_settings

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/badges", tags=["Badges"])

_settings = get_settings()


# ---------------------------------------------------------------------------
# Request / Response schemas
# ---------------------------------------------------------------------------


class BadgeSkill(BaseModel):
    """A single skill to embed in the badge."""

    name: str = Field(..., description="Canonical skill label (e.g. from ESCO)")
    description: str | None = Field(default=None, description="Optional elaboration")


class BadgeRequest(BaseModel):
    """Payload for issuing an Open Badges 3.0 credential."""

    recipient_name: str = Field(..., description="Display name of the badge earner")
    recipient_id: str = Field(
        ...,
        description="Unique identifier for the earner (e.g. email URI or DID)",
        json_schema_extra={"example": "did:example:user123"},
    )
    skills: list[BadgeSkill] = Field(
        ...,
        min_length=1,
        description="Skills to include in the credential",
    )
    badge_name: str = Field(
        default="UNMAPPED Skills Passport",
        description="Title of the badge / achievement",
    )
    badge_description: str = Field(
        default="Verified skills profile generated by the UNMAPPED protocol.",
        description="Longer description for the achievement",
    )


class BadgeResponse(BaseModel):
    """The issued Open Badges 3.0 credential as JSON-LD."""

    credential: dict = Field(
        ..., description="Full OpenBadgeCredential object (JSON-LD)"
    )


# ---------------------------------------------------------------------------
# Endpoint
# ---------------------------------------------------------------------------


@router.post(
    "/issue",
    response_model=BadgeResponse,
    summary="Issue an Open Badges 3.0 credential",
    description=(
        "Packages a list of extracted skills into a verifiable Open Badges 3.0 "
        "credential (JSON-LD) using the pyopenbadges library."
    ),
)
async def issue_badge(payload: BadgeRequest) -> BadgeResponse:
    """
    Build and return an Open Badges 3.0 credential.

    Uses pyopenbadges' built-in Pydantic models so we never manually
    construct JSON-LD schemas (per project rules).
    """
    try:
        # 1. Issuer profile
        issuer = Profile(
            id=_settings.ISSUER_ID,
            type="Profile",
            name=_settings.ISSUER_NAME,
            url=_settings.ISSUER_URL,
        )

        # 2. Achievement – embeds all skills in the description
        skills_summary = "; ".join(
            s.name + (f" – {s.description}" if s.description else "")
            for s in payload.skills
        )
        achievement = Achievement(
            id=f"{_settings.ISSUER_URL}/achievements/{uuid.uuid4()}",
            type="Achievement",
            name=payload.badge_name,
            description=f"{payload.badge_description}\n\nSkills: {skills_summary}",
            issuer=issuer,
        )

        # 3. Credential (Verifiable Credential envelope)
        credential = OpenBadgeCredential(
            id=f"{_settings.ISSUER_URL}/credentials/{uuid.uuid4()}",
            type=["VerifiableCredential", "OpenBadgeCredential"],
            issuer=issuer,
            issuanceDate=datetime.now(tz=timezone.utc),
            credentialSubject=AchievementSubject(
                id=payload.recipient_id,
                type="AchievementSubject",
                achievement=achievement,
            ),
        )

        # Serialize through Pydantic → dict (JSON-LD compatible)
        credential_dict = credential.model_dump(mode="json", exclude_none=True)

    except Exception as exc:
        logger.exception("Badge issuance failed")
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    return BadgeResponse(credential=credential_dict)
